name: Setup Rust
description: Configures the Rust toolchain
inputs:
  toolchain:
    description: "The toolchain to use"
    required: true
    default: "stable"
  components:
    description: "The components to install"
    required: false
  shared_key:
    description: "The key to use for the shared cache"
    required: false
  tools:
    description: "The tools to install"
    required: false
  cache_backend:
    description: "The backend to use for the cache"
    required: false
    default: github
runs:
  using: "composite"
  steps:
    - uses: dtolnay/rust-toolchain@stable
      id: setup-rust
      with:
        toolchain: ${{ inputs.toolchain }}
        components: ${{ inputs.components }}

    - uses: Swatinem/rust-cache@v2
      if: ${{ inputs.shared_key && inputs.cache_backend == 'github' }}
      with:
        prefix-key: "v0-rust-${{ steps.setup-rust.outputs.cachekey }}"
        shared-key: ${{ inputs.shared_key }}

    - uses: ubicloud/rust-cache@v2
      if: ${{ inputs.shared_key && inputs.cache_backend == 'ubicloud' }}
      with:
        prefix-key: "v0-rust-${{ steps.setup-rust.outputs.cachekey }}"
        shared-key: ${{ inputs.shared_key }}

    - uses: taiki-e/install-action@v2
      if: ${{ inputs.tools }}
      with:
        tool: ${{ inputs.tools }}

    - name: Install LLVM and Clang
      if: ${{ runner.os == "Windows" }}
      uses: KyleMayes/install-llvm-action@v2
      with:
        version: "20"
        directory: ${{ runner.temp }}/llvm
        env: true
