name: Setup Rust
description: Configures the Rust toolchain
inputs:
  toolchain:
    description: "The toolchain to use"
    required: true
    default: "stable"
  components:
    description: "The components to install"
    required: false
  shared_key:
    description: "The key to use for the shared cache"
    required: false
  tools:
    description: "The tools to install"
    required: false
  nightly_bypass:
    description: "Enable the RUSTC_BOOTSTRAP=1 flag"
    required: false
    default: false
runs:
  using: "composite"
  steps:
    - uses: dtolnay/rust-toolchain@stable
      id: setup-rust
      with:
        toolchain: ${{ inputs.toolchain }}
        components: ${{ inputs.components }}

    - uses: Swatinem/rust-cache@v2
      with:
        prefix-key: "v0-rust-${{ steps.setup-rust.outputs.cachekey }}"
        cache-on-failure: true
        shared-key: ${{ inputs.shared_key }}

    - name: Setup problem matcher
      shell: bash
      run: echo "::add-matcher::${{ github.action_path }}/matcher.json"

    - uses: taiki-e/install-action@v2
      if: ${{ inputs.tools }}
      with:
        tool: ${{ inputs.tools }}

    - name: Install LLVM and Clang
      if: ${{ runner.os == 'Windows' }}
      uses: KyleMayes/install-llvm-action@v2
      with:
        version: "20"
        directory: ${{ github.workspace }}/.runner/llvm

    - name: Set up nightly bypass
      shell: bash
      if: ${{ inputs.nightly_bypass == 'true' }}
      run: |
        echo "RUSTC_BOOTSTRAP=1" >> $GITHUB_ENV

    - name: Setup env
      shell: bash
      run: |
        echo "RUST_TOOLCHAIN=${{ inputs.toolchain }}" >> $GITHUB_ENV
