[workspace]
allow_dirty = true
changelog_update = false
release_always = false
pr_branch_prefix = "automation/cargo-release"
max_analyze_commits = 0
git_release_body = """
[<img alt="crates.io" src="https://img.shields.io/badge/crates.io-v{{ version }}-orange?labelColor=5C5C5C" height="20">](https://crates.io/crates/{{ package }}/{{ version }}) [<img alt="docs.rs" src="https://img.shields.io/badge/docs.rs-v{{ version }}-blue?labelColor=5C5C5C" height="20">](https://docs.rs/{{ package }}/{{ version }})

{{ changelog }}
"""

[[package]]
name = "tinc"
version_group = "tinc"

[[package]]
name = "tinc-build"
version_group = "tinc"

[[package]]
name = "tinc-derive"
version_group = "tinc"

[[package]]
name = "tinc-cel"
version_group = "tinc"

[[package]]
name = "tinc-pb-prost"
version_group = "tinc"

[[package]]
name = "scuffle-metrics"
version_group = "metrics"

[[package]]
name = "scuffle-metrics-derive"
version_group = "metrics"

[[package]]
name = "scuffle-bootstrap"
version_group = "bootstrap"

[[package]]
name = "scuffle-bootstrap-derive"
version_group = "bootstrap"
