exclude = ["crates/workspace-hack/Cargo.toml"]

[formatting]
reorder_keys = false

[[rule]]
include = ["**/Cargo.toml"]
keys = ["dependencies", "dev-dependencies", "build-dependencies"]

[rule.formatting]
reorder_keys = true
reorder_inline_tables = true
reorder_arrays = true
indent_tables = true
column_width = 100
