[package]
name = "scuffle-amf0"
version = "0.1.1"
edition = "2024"
license = "MIT OR Apache-2.0"
description = "A pure-rust implementation of AMF0 encoder and decoder."
repository = "https://github.com/scufflecloud/scuffle"
keywords = ["amf0", "rtmp", "flash", "video", "flv"]

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(coverage_nightly)'] }

[dependencies]
serde = "1.0.219"
bytes = "1.10.1"
byteorder = "1.5"
num-traits = "0.2"
num-derive = "0.4"
thiserror = "2.0"
scuffle-workspace-hack.workspace = true

[dev-dependencies]
serde = { version = "1.0.219", features = ["derive"] }
