[package]
name = "tinc-derive"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2" }
quote = { version = "1.0" }
proc-macro2 = { version = "1.0" }
scuffle-workspace-hack.workspace = true
