[package]
name = "tinc-pb"
version = "0.1.0"
edition = "2024"

[dependencies]
prost = "0.13.5"
prost-types = "0.13.5"
scuffle-workspace-hack.workspace = true

[build-dependencies]
prost-build = "0.13.5"
