name: Fmt
runs:
  using: "composite"
  steps:
    - name: Install taplo
      shell: bash
      run: curl -fsSL https://github.com/tamasfe/taplo/releases/latest/download/taplo-full-linux-x86_64.gz | gzip -d - | install -m 755 /dev/stdin /usr/local/bin/taplo

    - name: cargo fmt (rust)
      shell: bash
      run: cargo fmt --check

    - name: taplo fmt (toml)
      shell: bash
      run: taplo fmt --check
