[[scuffle-rtmp]]
category = "refactor"
description = "refactor to be more ergonomic and efficient"
breaking = true
authors = ["@TroyKomodo", "@lennartkloock"]

[[scuffle-flv]]
category = "refactor"
description = "refactor to be more ergonomic and efficient"
breaking = true
authors = ["@lennartkloock"]
