[[scuffle-http]]
category = "chore"
description = "bump h3-quinn to 0.0.9"
breaking = true
authors = ["@troykomodo"]

[[scuffle-http]]
category = "chore"
description = "bump h3 to 0.0.7"
breaking = true
authors = ["@troykomodo"]
