[[scuffle-ffmpeg]]
authors = ["@Juliapixel"]
category = "feat"
description = "Add `AudioFrame::format`"

[[scuffle-ffmpeg]]
authors = ["@Juliapixel"]
breaking = true
category = "feat"
description = "change `AudioFrame::channel_layout` and `GenericDecoder::time_base`'s return types to their non-ffi counterparts"
