[[scuffle-aac]]
category = "chore"
description = "fix changelog entry & release process"
authors = ["@troykomodo", "@SimaoMoreira5228", "@philipch07"]

[[scuffle-bytes-util]]
category = "chore"
description = "fix changelog entry & release process"
authors = ["@troykomodo", "@SimaoMoreira5228", "@philipch07"]

[[scuffle-amf0]]
category = "chore"
description = "fix changelog entry & release process"
authors = ["@troykomodo", "@SimaoMoreira5228", "@philipch07"]

[[scuffle-av1]]
category = "chore"
description = "fix changelog entry & release process"
authors = ["@troykomodo", "@SimaoMoreira5228", "@philipch07"]

[[scuffle-batching]]
category = "chore"
description = "fix changelog entry & release process"
authors = ["@troykomodo", "@SimaoMoreira5228", "@philipch07"]

[[scuffle-bootstrap]]
category = "chore"
description = "fix changelog entry & release process"
authors = ["@troykomodo", "@SimaoMoreira5228", "@philipch07"]

[[scuffle-context]]
category = "chore"
description = "fix changelog entry & release process"
authors = ["@troykomodo", "@SimaoMoreira5228", "@philipch07"]

[[scuffle-future-ext]]
category = "chore"
description = "fix changelog entry & release process"
authors = ["@troykomodo", "@SimaoMoreira5228", "@philipch07"]

[[postcompile]]
category = "chore"
description = "fix changelog entry & release process"
authors = ["@troykomodo", "@SimaoMoreira5228", "@philipch07"]

[[scuffle-settings]]
category = "chore"
description = "fix changelog entry & release process"
authors = ["@troykomodo", "@SimaoMoreira5228", "@philipch07"]

[[scuffle-signal]]
category = "chore"
description = "fix changelog entry & release process"
authors = ["@troykomodo", "@SimaoMoreira5228", "@philipch07"]

[[scuffle-bootstrap-telemetry]]
category = "chore"
description = "fix changelog entry & release process"
authors = ["@troykomodo", "@SimaoMoreira5228", "@philipch07"]

[[scuffle-http]]
category = "chore"
description = "fix changelog entry & release process"
authors = ["@troykomodo", "@SimaoMoreira5228", "@philipch07"]

[[scuffle-pprof]]
category = "chore"
description = "fix changelog entry & release process"
authors = ["@troykomodo", "@SimaoMoreira5228", "@philipch07"]

[[scuffle-metrics]]
category = "chore"
description = "fix changelog entry & release process"
authors = ["@troykomodo", "@SimaoMoreira5228", "@philipch07"]

[[scuffle-expgolomb]]
category = "chore"
description = "fix changelog entry & release process"
authors = ["@troykomodo", "@SimaoMoreira5228", "@philipch07"]

[[scuffle-ffmpeg]]
category = "chore"
description = "fix changelog entry & release process"
authors = ["@troykomodo", "@SimaoMoreira5228", "@philipch07"]

[[nutype-enum]]
category = "chore"
description = "fix changelog entry & release process"
authors = ["@troykomodo", "@SimaoMoreira5228", "@philipch07"]

[[scuffle-mp4]]
category = "chore"
description = "fix changelog entry & release process"
authors = ["@troykomodo", "@SimaoMoreira5228", "@philipch07"]

[[scuffle-h264]]
category = "chore"
description = "fix changelog entry & release process"
authors = ["@troykomodo", "@SimaoMoreira5228", "@philipch07"]

[[scuffle-h265]]
category = "chore"
description = "fix changelog entry & release process"
authors = ["@troykomodo", "@SimaoMoreira5228", "@philipch07"]

[[scuffle-flv]]
category = "chore"
description = "fix changelog entry & release process"
authors = ["@troykomodo", "@SimaoMoreira5228", "@philipch07"]

[[scuffle-rtmp]]
category = "chore"
description = "fix changelog entry & release process"
authors = ["@troykomodo", "@SimaoMoreira5228", "@philipch07"]

[[scuffle-transmuxer]]
category = "chore"
description = "fix changelog entry & release process"
authors = ["@troykomodo", "@SimaoMoreira5228", "@philipch07"]

[[tinc]]
category = "chore"
description = "fix changelog entry & release process"
authors = ["@troykomodo", "@SimaoMoreira5228", "@philipch07"]

[[openapiv3_1]]
category = "chore"
description = "fix changelog entry & release process"
authors = ["@troykomodo", "@SimaoMoreira5228", "@philipch07"]
