[[tinc]]
category = "feat"
description = "generate root module for including all protos"
authors = ["@troykomodo"]

[[tinc]]
category = "fix"
description = "fix codegen for non-message service inputs"
authors = ["@troykomodo"]

[[scufflecloud-auth-server]]
category = "feat"
description = "initial implementation"
authors = ["@troykomodo"]

[[scufflecloud-proto]]
category = "feat"
description = "initial implementation"
authors = ["@troykomodo"]
