[[postcompile]]
category = "chore"
description = "bumped cargo-metadata to `0.20`"
authors = ["troykomodo"]

[[scuffle-batching]]
category = "chore"
description = "bumped criterion to `0.6`"
authors = ["troykomodo"]

[[scuffle-bootstrap]]
category = "chore"
description = "refactor the telemetry sub-crate out into parent directory"
authors = ["troykomodo"]

[[scuffle-bootstrap-telemetry]]
category = "chore"
description = "bump opentelemetry sdk to `0.30`"
authors = ["troykomodo"]
breaking = true

[[scuffle-metrics]]
category = "chore"
description = "bump opentelemetry sdk to `0.30`"
authors = ["troykomodo"]
breaking = true

[[scuffle-pprof]]
category = "chore"
description = "bump pprof to `0.15`"
authors = ["troykomodo"]
breaking = true

[[tinc]]
category = "chore"
description = "bump mediatype to `0.20`"
authors = ["troykomodo"]
