[[scuffle-http]]
category = "chore"
description = "update to h3 0.0.8"
authors = ["@lennartkloock"]

[[scuffle-http]]
category = "chore"
description = "update to h3-quinn 0.0.10"
authors = ["@lennartkloock"]
