[[scuffle-amf0]]
category = "docs"
description = "cleaned up documentation"
authors = ["troykomodo"]

[[scuffle-bootstrap]]
category = "chore"
description = "cleaned up dev-dependencies"
authors = ["troykomodo"]

[[scuffle-bootstrap-telemetry]]
category = "chore"
description = "cleaned up dev-dependencies"
authors = ["troykomodo"]

[[scuffle-context]]
category = "chore"
description = "cleaned up dev-dependencies"
authors = ["troykomodo"]

[[scuffle-ffmpeg]]
category = "chore"
description = "cleaned up dev-dependencies"
authors = ["troykomodo"]

[[scuffle-http]]
category = "chore"
description = "cleaned up dev-dependencies"
authors = ["troykomodo"]

[[scuffle-metrics]]
category = "chore"
description = "cleaned up dev-dependencies"
authors = ["troykomodo"]

[[scuffle-rtmp]]
category = "chore"
description = "cleaned up dev-dependencies"
authors = ["troykomodo"]

[[scuffle-signal]]
category = "chore"
description = "cleaned up dev-dependencies"
authors = ["troykomodo"]

[[tinc]]
category = "chore"
description = "cleaned up grouped dependencies"
authors = ["troykomodo"]

[[openapiv3_1]]
category = "docs"
description = "update docs to avoid clippy docsrs ICE"
authors = ["troykomodo"]
