[[scuffle-bootstrap]]
category = "chore"
description = "bump opentelemetry to 0.29"
breaking = true
authors = ["@troykomodo"]

[[scuffle-bootstrap]]
category = "chore"
description = "bump opentelemetry_sdk to 0.29"
breaking = true
authors = ["@troykomodo"]

[[scuffle-bootstrap]]
category = "chore"
description = "bump opentelemetry-appender-tracing to 0.29"
breaking = true
authors = ["@troykomodo"]

[[scuffle-bootstrap]]
category = "chore"
description = "bump tracing-opentelemetry to 0.30"
breaking = true
authors = ["@troykomodo"]

[[scuffle-metrics]]
category = "chore"
description = "bump opentelemetry to 0.29"
breaking = true
authors = ["@troykomodo"]

[[scuffle-metrics]]
category = "chore"
description = "bump opentelemetry_sdk to 0.29"
breaking = true
authors = ["@troykomodo"]
