[[tinc]]
category = "feat"
description = "allow generating root module which will include all protos"
authors = ["@troykomodo"]

[[tinc]]
category = "fix"
description = "fix codegen for non-message service inputs"
authors = ["@troykomodo"]
