[[postcompile]]
category = "fix"
description = "Fix compile times with postcompile"
breaking = true
authors = ["@troykomodo"]

[[postcompile]]
category = "feat"
description = "Add test running ability"
breaking = true
authors = ["@troykomodo"]
