[package]
name = "tinc"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.215", features = ["derive"] }
schemars = { version = "0.8.22", features = ["chrono"] }
tonic = "0.12.3"
prost = "0.13.5"
chrono = "0.4.36"
prost-types = "0.13.5"
serde_json = "1.0.115"
itoa = "1.0.1"
ryu = "1.0.14"
scuffle-workspace-hack.workspace = true
