[package]
name = "tinc"
version = "0.1.0"
edition = "2024"
description = "GRPc to REST transcoding library"
repository = "https://github.com/scufflecloud/scuffle"
authors = ["Scuffle <opensource@scuffle.cloud>"]
readme = "README.md"
documentation = "https://docs.rs/tinc"
license = "MIT OR Apache-2.0"
keywords = ["grpc", "protobuf", "tonic", "rest"]

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(coverage_nightly)'] }

[dependencies]
http = "1"
axum = "0.8"
http-body = "1"
http-body-util = "0.1.0"
bytes = "1.6.0"

tonic = { version = "0.13.0", optional = true }
prost = { version = "0.13.5", optional = true }
prost-types = { version = "0.13.5", optional = true }

serde = "1.0.215"
serde_json = "1.0.115"
serde_repr = "0.1.20"

schemars = { version = "1.0.0-alpha.17", features = ["chrono04"] }

chrono = { version = "0.4.36", features = ["serde"] }
thiserror = "2"
tonic-types = "0.13.0"

# Media Types
headers-accept = "0.1.4"
mediatype = "0.19.20"
serde_urlencoded = "0.7.1"
serde_qs = "0.15.0"
memchr = "2.4"

linkme = "0.3"
num-traits = "0.2.19"

# Parsing / Formatting numbers
itoa = "1.0.1"
ryu = "1.0.14"
regex = "1"

linear-map = "1.2.0"
float-cmp = "0.10.0"

tinc-derive.workspace = true
tinc-cel = { workspace = true, features = ["runtime"] }

scuffle-workspace-hack.workspace = true

[features]
prost = ["dep:prost", "dep:prost-types"]
tonic = ["dep:tonic"]
default = ["prost", "tonic"]
