[package]
name = "tinc-pb-prost"
version = "0.1.0"
edition = "2024"
description = "Protobuf generated schama for tinc"
repository = "https://github.com/scufflecloud/scuffle"
authors = ["Scuffle <opensource@scuffle.cloud>"]
readme = "README.md"
documentation = "https://docs.rs/tinc-pb"
license = "MIT OR Apache-2.0"
keywords = ["grpc", "protobuf", "prost", "codegen"]

[dependencies]
prost = "0.13.5"
prost-types = "0.13.5"
scuffle-workspace-hack.workspace = true

[build-dependencies]
prost-build = "0.13.5"
