name: Semver-checks
inputs:
  pr_number:
    description: "The PR number"
    required: true
runs:
  using: "composite"
  steps:
    - name: Run xtask semver checks (against main branch)
      id: semver_checks
      shell: bash
      env:
        RUSTFLAGS: "--cfg reqwest_unstable"
      run: |
        result=$(cargo xtask semver-checks --disable-hakari)
        echo "checks_output<<EOF" >> $GITHUB_OUTPUT
        echo "$result" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: Add/update PR comment
      uses: thollander/actions-comment-pull-request@v3
      with:
        message: ${{ steps.semver_checks.outputs.checks_output }}
        pr-number: ${{ inputs.pr_number }}
        comment-tag: semver-checks
