name: Clippy
inputs:
  powerset:
    description: "Whether to run Clippy on Powerset"
    required: false
    default: false
runs:
  using: "composite"
  steps:
    - name: Disable Hakari
      shell: bash
      run: cargo hakari disable

    - name: Run Clippy
      if: ${{ inputs.powerset == 'false' }}
      shell: bash
      run: cargo clippy --all-features --all-targets --no-deps -- -Dwarnings -Aclippy::collapsible_if

    - name: Run Clippy on Powerset
      if: ${{ inputs.powerset == 'true' }}
      shell: bash
      run: just powerset clippy -- --all-targets --no-deps -- -Dwarnings -Aclippy::collapsible_if
