name: Release-checks
inputs:
  pr_number:
    description: "The PR number"
    required: true
runs:
  using: "composite"
  steps:
    - name: Install
      shell: bash
      run: |
        cargo binstall release-plz --git https://github.com/ScuffleCloud/release-plz.git --force -y

    - name: Run release-plz update check
      id: semver_checks
      shell: bash
      continue-on-error: true
      env:
        RUSTFLAGS: "--cfg reqwest_unstable"
      run: |
        release-plz update --disable-dependant-updates --no-changelog --check-only --exit-status 2> /tmp/.release-plz.stderr 1> /tmp/.release-plz.stdout

    - name: PR Body
      shell: bash
      env:
        MESSAGE: "${{ steps.semver_checks.outcome == 'failure' && '❌ Release Checks Failed\n\nYou need to update the versions on the following packages:' || '✅ All package versions up-to-date!' }}"
      run: |
        {
          printf '## %s\n\n' "$MESSAGE"
          cat /tmp/.release-plz.stdout
          printf '\n\n<details><summary>Release-plz output</summary>\n\n```\n'
          sed -E "s/\x1B\[[0-9;]*[mK]//g" /tmp/.release-plz.stderr
          printf '```\n\n</details>'
        } | tee /tmp/.release-checks-body $GITHUB_STEP_SUMMARY

        # Print stderr to the log for debugging
        cat /tmp/.release-plz.stderr

    - name: Add/update PR comment
      # skip commenting the summary on forked PRs
      if: ${{ !github.event.pull_request.head.repo.fork && inputs.pr_number != null }}
      uses: thollander/actions-comment-pull-request@v3
      with:
        file-path: /tmp/.release-checks-body
        pr-number: ${{ inputs.pr_number }}
        comment-tag: semver-checks

    - name: Fail
      if: ${{ steps.semver_checks.outcome == 'failure' }}
      shell: bash
      run: |
        echo "A package versions not up-to-date"
        exit 1
