name: ci

on:
  push:
    branches:
      - automation/brawl/try/*
      - automation/brawl/merge/*

  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  # By default, when a action is run against a PR it will use a merge commit from the target branch & the PR branch. We want to use just the PR branch.
  # So this changes the SHA to the PR branch SHA or falls back to the current SHA (if its not a PR)
  # https://github.com/actions/checkout/issues/426
  SHA: ${{ github.event.pull_request.head.sha || github.sha }}

defaults:
  run:
    shell: bash

permissions:
  # enable writing for semver-checks so it can write a pr comment
  pull-requests: write

jobs:
  matrix_prep:
    name: Matrix Prep
    runs-on: ubuntu-24.04
    outputs:
      matrix: ${{ steps.compute.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ env.SHA }}

      - name: Switch to Branch
        run: |
          set -xeo pipefail
          git switch -C ${{ github.ref_name }}

      - name: Run matrix prep
        id: compute
        env:
          JSON_INPUT: ${{ toJson(github) }}
        run: |
          set -xeo pipefail
          echo $JSON_INPUT | python3 .github/scripts/ci-matrix-prep.py | tee -a $GITHUB_OUTPUT

  jobs:
    name: ${{ matrix.job_name || 'Jobs' }}
    needs: matrix_prep
    strategy:
      fail-fast: ${{ github.event_name == 'push' }}
      matrix:
        include: ${{ fromJson(needs.matrix_prep.outputs.matrix) }}
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: samypr100/setup-dev-drive@v3
        if: ${{ runner.os == 'Windows' }}
        with:
          drive-size: 80GB
          mount-path: ${{ github.workspace }}
          trusted-dev-drive: true
          env-mapping: |
            CARGO_HOME,{{ DEV_DRIVE }}/.runner/.cargo
            RUSTUP_HOME,{{ DEV_DRIVE }}/.runner/.rustup

      - uses: actions/checkout@v4
        with:
          ref: ${{ env.SHA }}
          path: wd

      - name: Move files to root
        run: |
          shopt -s dotglob
          mv wd/* .
          rmdir wd
          shopt -u dotglob

      - name: Switch to Branch
        run: |
          set -xeo pipefail
          git switch -C ${{ github.ref_name }}

      - name: Setup FFmpeg
        if: ${{ matrix.ffmpeg != null }}
        uses: ./.github/actions/setup-ffmpeg
        with: ${{ matrix.ffmpeg }}

      - name: Setup Rust
        if: ${{ matrix.rust != null }}
        uses: ./.github/actions/setup-rust
        with: ${{ matrix.rust }}

      - name: Setup Protoc
        if: ${{ matrix.setup_protoc }}
        uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Secrets
        if: ${{ matrix.secrets != null }}
        run: |
          set -eo pipefail
          secrets='${{ toJson(secrets) }}'

          for secret in $(echo '${{ toJson(matrix.secrets) }}' | jq -r '.[]'); do
            value=$(echo "$secrets" | jq -r --arg key "$secret" '.[$key]')
            echo "$secret=$value" >> $GITHUB_ENV
            echo "Setting $secret to $value"
          done

      - name: Run ./.github/actions/ci/${{ matrix.job }}
        uses: ./.github/actions/ci/dynamic
        with:
          uses: ./.github/actions/ci/${{ matrix.job }}
          with: |
            ${{ toJson(matrix.inputs) }}

  brawl-done:
    runs-on: ubuntu-24.04
    needs: [matrix_prep, jobs]
    if: ${{ !cancelled() && github.event_name == 'push' }}
    steps:
      - name: calculate the correct exit status
        run: jq --exit-status 'all(.result == "success" or .result == "skipped")' <<< '${{ toJson(needs) }}'
