name: Release-plz PR

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * 1'  # Monday at 12:00 UTC
    - cron: '0 12 * * 3'  # Wednesday at 12:00 UTC
    - cron: '0 12 * * 6'  # Saturday at 12:00 UTC

env:
  RUST_TOOLCHAIN: nightly

jobs:
  release-plz-pr:
    name: Cargo Release PR
    runs-on: ubicloud-standard-8
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: ./.github/actions/setup-rust
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN }}
          shared-key: cargo-release-pr
          tools: just,cargo-binstall
          cache-backend: ubicloud

      - name: Install
        shell: bash
        run: |
          cargo binstall release-plz --git https://github.com/ScuffleCloud/release-plz.git --force -y

      - name: Pr Title
        if: ${{ github.event_name == 'schedule' }}
        run: |
          echo "Automated release workflow" | tee /tmp/pr-body.txt $GITHUB_STEP_SUMMARY

      - name: Pr Title
        if: ${{ github.event_name == 'schedule' }}
        run: |
          echo "Release workflow triggered by @${{ github.actor }}" | tee /tmp/pr-body.txt $GITHUB_STEP_SUMMARY

      - name: Create release
        run: |
          set -eo pipefail
          cargo xtask change-logs generate
          release-plz update --disable-dependant-updates | tee -a /tmp/pr-body.txt $GITHUB_STEP_SUMMARY

      # Check if any files changed
      - name: Check if anything changed
        id: changed
        run: |
          result=$((git diff --exit-code > /dev/null && echo '0') || echo '1')
          echo "result=$result" >> $GITHUB_OUTPUT

      - name: Create github PR
        uses: peter-evans/create-pull-request@v7
        if: ${{ steps.changed.outputs.result == 1 }}
        with:
          title: Release Crates
          body-path: /tmp/pr-body.txt
          branch: automation/cargo-release
          labels: release,automated,change-log-not-required
          commit-message: |
            release crates
          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          sign-commits: true
          reviewers: ${{ github.actor }}
